version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"

    volumes:
      - .:/usr/src/app
      - /usr/scr/app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
