version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    # Add any MongoDB configurations or volumes as needed
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
